### ISSUE TITLE
API Key Expired

### ISSUE THREAD

**Issue by mmgrigorova** [vueschool/vue-masterclass#10]
When I run the app locally and try to Register I get an error in Dev Tools console: 
`message: "{\"error\":{\"code\":400,\"message\":\"API key expired. Please renew the API key.\",\"errors\":[{\"message\":\"API key expired. Please renew the API key.\",\"domain\":\"global\",\"reason\":\"badRequest\"}],\"status\":\"INVALID_ARGUMENT\",\"details\":[{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"API_KEY_INVALID\",\"domain\":\"googleapis.com\",\"metadata\":{\"service\":\"identitytoolkit.googleapis.com\"}}]}}"
`
Do I need to make any changes on my side? Thanks!

**Comment by danielkellyio** [comment]
please provide your own API key for Google cloud. :) 
Apologies for the very late reply!
