### ISSUE TITLE
Strange behavior of the VueSchool.io

### ISSUE THREAD

**Issue by MoskalenkoM** [vueschool/vue-masterclass#3]
Hello!
You, Vue School, provide the functionality of subscriptions to your courses and link a bank card to payment methods, but you do not give the functionality of unsubscribing from courses and deleting a bank card from my personal account on your site. Or you have deliberately hidden this functionality so that it is difficult to find it on your site. This looks like a scam, because you are trying to charge money from my card and do not respond to an email about how to unsubscribe from subscriptions to your courses.
How do I unsubscribe from your courses?
How can I stop your attempts to debit money from my bank card?
How do I delete a bank card from my personal account on your website?

**Comment by MoskalenkoM** [comment]
You still do not allow me to untie my bank card and do not give me the opportunity to unsubscribe from your subscriptions. It looks like a scam.

**Comment by danielkellyio** [comment]
@MoskalenkoM So sorry for the issues you are having! This isn't my department so I'm not in total control of how to help but I've relayed the message to those who can and we're in the process of fixing the issue. Look out for an email from the Vue School team in the near future for details on the resolution

**Comment by bartek7774** [comment]
Problem still exists. It's unbelievable.
