### ISSUE TITLE
Source code portions relying on firebase doesn't work with firebase v9

### ISSUE THREAD

**Issue by bmc-atx** [vueschool/vue-masterclass#4]
The whole Firebase series in the videos is not working (as of December 2021). That’s because the install instructions provided in these Vue School videos (“npm install —save firebase”) now installs version 9 of Firebase. Version 9 (I have discovered after grinding through research the past several hours), now installs what is named “Modular SDK”. That version uses different terminology than previous versions, so nothing with firebase as described in these Vue School videos works with version 9 installed.

For instance, writing “import firebase from ‘firebase’ and “firebase.initializeApp” in main.js DOES NOT WORK with version 9. Instead, you have to type “import { initializeApp } from 'firebase/app'” and “initializeApp(firebaseConfig).

Likewise, the video (and source code) instructions for ThreadShow in this video returns an error because you can’t use “import firebase from ‘firebase’” in the script tag. I haven’t figured out what you do instead.

To code along with the videos, you need to install firebase v 8. After 3 hours of research, I haven’t figured out how to install version 8 (Google’s site is devoid of info on this). I’m guessing it’s something like npm i firebase@8 or something like that.

This is defcon 1 stuff that Vue School needs to fix right away. The series comes to a screeching halt otherwise

**Comment by danielkellyio** [comment]
Hey @bmc-atx, 
my apologies for the trouble! You are exactly right that using the command
```
npm install firebase
```
installs the latest version of firebase which at this point in time is indeed Firebase 9. You are also spot on in your solution for installing version 8 :) 

```
npm install firebase@8
```

If for some reason version 8 doesn't work for you, you can also try the compat package that aims to make version 9 backwards compatible with version 8. 

If you look in the comments section of the [Firebase Installation and Setup Video](https://vueschool.io/lessons/firebase-setup-and-installation) in the course, you should be able to find more information on both solutions. 

Hope this helps! :)
